---
title: Fort Toulouse - Fort Jackson
email: tgray.it@gmail.com
description: Come visit and see the recreated 1751 Fort Toulouse, Creek Indian houses,
  and the partially restored 1814 American Fort Jackson! You can also see a 1,000-year-old
  Indian mound, and experience nature on the William Bartram Nature Trail!
baseurl: ''
url: "/"
future: true
markdown: kramdown
exclude:
- vendor/bundle
- Gemfile
- Gemfile.lock
google_analytics: UA-41841096-1
collections:
  home: 
  frontierdays: 
  pages:
    output: true
  posts:
    permalink: journal/:path/
  explore:
    output: true
    permalink: "/:path/"
  events:
    output: true
    permalink: events/:path/
  reenactors:
    output: true
sass:
  load_paths:
  - _sass
  - _sass/animate
  - _sass/jeet
mini_magick:
  thumbnail:
    source: images
    destination: images_resized/thumbnail/images
    resize: 500x300^
    gravity: center
    extent: 500x300
  medium:
    source: images
    destination: images_resized/medium/images
    resize: 800x500^
    gravity: center
    extent: 800x500
  large:
    source: images
    destination: images_resized/large/images
    resize: 1400x800^
    gravity: center
    extent: 1400x800
  large-uploads:
    source: uploads
    destination: images_resized/large/uploads
    resize: 1400x800^
    gravity: center
    extent: 1400x800
  thumbnail-uploads:
    source: uploads
    destination: images_resized/thumbnail/uploads
    resize: 500x300^
    gravity: center
    extent: 500x300
  medium-uploads:
    source: uploads
    destination: images_resized/medium/uploads
    resize: 800x500^
    gravity: center
    extent: 800x500
